version: '3.8'

services:
  mysql-db:
    image: mysql:8.0
    container_name: root
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: crudlivros

    ports:
    - "3306:3306"
    cap_add:
      - SYS_NICE